def get_help():
    print("Utility Help")
    print("This utility can be called as per the following example:")
    print("------------------------------------------")
    print("ow command battletag platform region mode")
    print("------------------------------------------")
    print("ow [compulsory]")
    print("command {getpatchnotes, getachievements, getplatforms, getprofiles, getheroesstats/getmedals/getkills/gettime/getgames/getobjectives, gethelp} [compulsory]")
    print("battletag {eg: test#1212} [compulsory except for gethelp]")
    print("platform {pc, xbl, psn} [compulsory except for getpatchnotes, gethelp]")
    print("region {eu, us, kr, cn, global} [compulsory except for getpatchnotes, gethelp]")
    print("mode {quickplay, competitive} [optional except for getheroesstats]")
    print("hero {Tracer, Roadhog, Torbjoern, Lucio, Soldier76, etc} [optional. Retrieves hero stats when used with getheroesstats/getmedals/getkills/gettime/getgames/getobjectives]")
    print("------------------------------------------")