def get_help():
    print("Utility Help")
    print("This utility can be called as per the following example:")
    print("------------------------------------------")
    print("ow command battletag platform region mode")
    print("------------------------------------------")
    print("ow [compulsory]")
    print("command {getpatchnotes, getachievements, getplatforms, getprofiles, getheroesstats, gethelp} [compulsory]")
    print("battletag {eg: test#1212} [optional]")
    print("platform {pc, xbl, psn} [optional]")
    print("region {eu, us, kr, cn, global} [optional]")
    print("mode {quickplay, competitive} [optional]")
    print("------------------------------------------")